name: ${pluginName}
main: com.untamedears.realisticbiomes.RealisticBiomes
depend:
- CivModCore
version: ${version}
authors:
- mgrandi
- gispy-king
- jacobcole2000
- WildWeazel
- ProgrammerDan
- Numrufus
- Erocs
- danquist
- pruby
- Maxopoly
- BlackXnt
- Diet-Cola
- Aleksey-Terzi
description: ${description}
api-version: ${api_version}
permissions:
  rb.public:
    default: true
  rb.op:
    default: op
  rb.pickBiome:
    default: op
